### ISSUE TITLE
(Ubuntu 22) environment variable not found

### ISSUE THREAD

**Issue by SevenworksDev** [dankmeme01/globed#2]
I keep getting `[ERROR] - Uncaught status: 500 Internal Server Error: environment variable not found` running the central server on linux. I made a .env file and put this in my .bashrc file correctly and it was working yesterday and now its not. Ive restarted my terminal also and still didnt work.
```
GLOBED_SERVER_FILE_PATH="servers.json"
```

**Comment by dankmeme01** [comment]
Are you sure your setup is correct?

If it was working fine yesterday but stopped working now, then it is probably an issue with your setup, the central server hasn't been updated recently.

Make sure you are also using `export GLOBED_SERVER_FILE_PATH=...`, the "export" keyword is important if you are putting it inside .bashrc

**Comment by SevenworksDev** [comment]
I got it the servers to work but it crashes the geode mod

```
== Geode Information ==
Loader Version: v1.3.4
Installed mods: 8
Problems: 0

== Exception Information ==
Faulty Module: C:\WINDOWS\System32\KERNELBASE.dll
Faulty Mod: <Unknown>
Exception Code: e06d7363 (<Unknown>)
Exception Flags: 1
Exception Address: 7666D902 (KERNELBASE.dll + 13d902 (RaiseException + 98))
Number Parameters: 3
```

**Comment by dankmeme01** [comment]
@SevenworksDev sorry for late reply, but if you're still experiencing the issue on the newest versions of the mod then can you please post the full crashlog

**Comment by SevenworksDev** [comment]
I got it to not crash anymore on my end, thanks for trying to help anyways.
