### ISSUE TITLE
Feature request: Player pause icon

### ISSUE THREAD

**Issue by Bituvo** [dankmeme01/globed#25]
Players should have a pause icon (the two white rectangles) somewhere around them when they are paused. Their animation should also pause. This would require a protocol update.

**Comment by dankmeme01** [comment]
> This would require a protocol update

that's where you're wrong!

added in next update.

**Comment by Bituvo** [comment]
I thought it would :D

**Comment by dankmeme01** [comment]
It was already internally sent in v0.4.0, but only used to stop interpolation when the player is paused (to stop weird glitches). now it will also show an icon :)
