### ISSUE TITLE
Feature request: Auto-disconnect when closing the game

### ISSUE THREAD

**Issue by Bituvo** [dankmeme01/globed#26]
If you close the game and reopen it, you get a "Globed Error" saying that you are already connected.

**Comment by dankmeme01** [comment]
This is already a feature, make sure that you are closing the game properly (through the X button in main menu or the escape key) and that there's nothing causing the game to crash during closing. If you are doing everything right you will see a message in the logs:

`17:04:56 [Globed]: NetworkHandler deinit`

If you are sure you are doing everything correctly and don't see this, reopen the issue
