### ISSUE TITLE
UFOs are rendered incorrectly

### ISSUE THREAD

**Issue by Bituvo** [dankmeme01/globed#33]
![image](https://github.com/dankmeme01/globed/assets/90872694/92093b52-ce7b-4b4e-b728-00744c59c5b2)
For the same reason as the ship. The UFO's glow layer should be all the way in the back.

**Comment by dankmeme01** [comment]
I believe this (and the similar bug with the ship) is more of a game limitation, and can't be fixed easily without completely remaking the render system for players, so it won't be fixed for now
