### ISSUE TITLE
Any server software I can download?

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [dankmeme01/globed#4]
Is there anything I can download or compile to let me run a server off of Windows or Linux? I see options for config in the README.md but unless I missed something actually hosting the server isn't mentioned. This mod is sick, and I'd like to host a quick private session for me and my friends. Thanks

**Comment by SevenworksDev** [comment]
1. Use Ubuntu via WSL on Windows (reccomended) (make sure to `apt update && apt upgrade`)
2. Install rustc and cargo using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
3. Compile this repo using `cargo run --release --bin globed-central-server` and `cargo run --release --bin globed-game-server`
4. You have compiled the globed servers, Now setup the servers json and add it to your environment variables and you should be setup for local testing. If you want it public, look at this project called `localhost.run`, its fun.

**Comment by dankmeme01** [comment]
There are no distributed binaries, if you want to host a server you have to download the code and compile it yourself. But with rust it shouldn't be hard, another person already suggested you how to do it

**Comment by ruguysgoingtrickortreating** [comment]
Thank you guys! :)
