### ISSUE TITLE
Feature request: Player glow

### ISSUE THREAD

**Issue by Bituvo** [dankmeme01/globed#8]
Multiplayer icons should have glow (would this require a server update?)

**Comment by dankmeme01** [comment]
This was already added in the [v0.3.0](https://github.com/dankmeme01/globed/releases/tag/0.3.0) update two days ago, unless you mean something else.

**Comment by Bituvo** [comment]
I am using v0.3.1 and my icon's glow doesn't show for me.

**Comment by dankmeme01** [comment]
Do you mean specifically the glow on the progress indicator? That would make sense, as those icons don't have glow right now. Will be fixed in the next release

But if you mean the actual player icons then I don't know, I have tested it together with multiple players and it works fine.

**Comment by Bituvo** [comment]
Yeah, the progress indicator. I probably shoulda specified :P
